### ISSUE TITLE
Brak stylizacji - moderowanie przez

### ISSUE THREAD

**Issue by szogi1910** [lukasamd/MyBB-Style_Usernames#11]
Po aktywacji pluginy zamiast informacji o grupie jaka moderuje dany dział otrzymujemy komunikat
# STYLE_USERNAMES_UID0

**Comment by lukasamd** [comment]
![moderators1](https://cloud.githubusercontent.com/assets/1265016/15631883/50aadd68-257f-11e6-94a7-70fead953765.png)
![moderators2](https://cloud.githubusercontent.com/assets/1265016/15631882/50a7e2b6-257f-11e6-9e84-e2ab04027a91.png)
