### ISSUE TITLE
Deleted user's name isn't shown in the "last post" column, a placeholder is shown instead

### ISSUE THREAD

**Issue by HungryFeline** [lukasamd/MyBB-Style_Usernames#7]
Instead of displaying the user's name in a default color, it shows the name of a deleted user like ` #STYLE_USERNAMES_UID896#` but only in the "Last Post" column.

![mybb-colorized-usernames-bug](https://cloud.githubusercontent.com/assets/782759/9021708/80aca1ca-3851-11e5-8c63-2ea2a5dadc76.png)

**Comment by lukasamd** [comment]
Can't reproduce error, close.
