### ISSUE TITLE
Displaying #STYLE_USERNAMES_UID18#

### ISSUE THREAD

**Issue by rusty2009** [lukasamd/MyBB-Style_Usernames#8]
HI, thanks for this great plugin.

Their seems to be an issue with the updated version in as much as it just displays #STYLE_USERNAMES_UID18# (UID changes).

![user name](https://cloud.githubusercontent.com/assets/15684576/10991642/d89ae706-8456-11e5-99a1-c117b9df59cb.PNG)
![user name1](https://cloud.githubusercontent.com/assets/15684576/10991643/d89ec416-8456-11e5-827d-64f13a52cdfd.PNG)

I've attached a couple of screen shots do you know how this can be fixed?

Many thanks
Rusty.

**Comment by lukasamd** [comment]
Please use last stable version from releases tab.

**Comment by rusty2009** [comment]
Thank-you I will try it later :-)
